name: Deploy Theme to Server

on:
  push:
    branches:
      - main # Wichtig: Falls euer Branch 'master' heißt, ändere das hier in 'master' um!

jobs:
  web-deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: './*'
        remote_path: '/html/wordpress/wp-content/themes/agency-theme/'